### ISSUE TITLE
Rewrite it entirely... again

### ISSUE THREAD

**Issue by altf4** [project-slippi/slippi-launcher#168]
The last one went so well!

**Comment by NikhilNarayana** [comment]
:p

**Comment by vinceau** [comment]
This but unironically.

We have an ongoing frustration where we're dependent on `electron-webpack` for our build management but the dependency is no longer maintained. `electron-webpack` has issues with newer versions of `electron` v8+ where the source maps are not generated correctly which makes development a pain.

If we have any hope of upgrading Electron we may need to ditch `electron-webpack` completely in favour of just managing our own build configurations. We don't necessarily have to do this from scratch since there are plenty of boilerplates out there. A trusted one is [this one](https://electron-react-boilerplate.js.org) for example.

We might also want to take this opportunity to take advantage of `preload.js` for our bridge communication so we can hopefully disable node integration in the renderer thread.

**Comment by NikhilNarayana** [comment]
See #222 for further details
