### ISSUE TITLE
bug: replays sent to User\Documents\Slippi despite having custom directory set

### ISSUE THREAD

**Issue by Nyanaro** [project-slippi/slippi-launcher#214]
[Image](https://cdn.discordapp.com/attachments/148120887751606272/875104691644686416/Slippi_Launcher_vdrmpZpNpn.png) [Image2](https://cdn.discordapp.com/attachments/148120887751606272/875104689002258462/explorer_ZGI3O9QNox.png)

The custom replay root directory is not functioning as intended, files are being sent to User\Documents\Slippi despite having custom directory set. The same custom directory worked in a previous version (not sure which).
![explorer_ZGI3O9QNox](https://user-images.githubusercontent.com/22597387/129094562-b4f06ffd-11dd-4a83-b814-f28962c79e49.png)
![Slippi_Launcher_vdrmpZpNpn](https://user-images.githubusercontent.com/22597387/129094567-3de34ad8-f860-4551-9589-474a22b655e5.png)

**Comment by cnkeats** [comment]
The replay path is (currently) controlled by Dolphin, and the setting you are adjusting is just for the launcher to find them. I say currently because in the next launcher update this functionality will be added and will work like you are anticipating it to.

The current workaround is to adjust the replay directory by going in the launcher from Settings --> Netplay --> Configure Dolphin --> Config --> Slippi

**Comment by Nyanaro** [comment]
> The replay path is (currently) controlled by Dolphin, and the setting you are adjusting is just for the launcher to find them. I say currently because in the next launcher update this functionality will be added and will work like you are anticipating it to.
> 
> The current workaround is to adjust the replay directory by going in the launcher from Settings --> Netplay --> Configure Dolphin --> Config --> Slippi

I see, thank you very much
